### ISSUE TITLE
BFT-fabric 2.2.0 LTS release

### ISSUE THREAD

**Issue by AgentArcLab** [SmartBFT-Go/fabric#195]
Is there a plan to create a branch based on fabric 2.2.0 LTS release version? thanks!

**Comment by yacovm** [comment]
Yes

**Comment by AgentArcLab** [comment]
> Yes

Great!

**Comment by yacovm** [comment]
We are [starting](https://github.com/SmartBFT-Go/fabric/pull/273) from the release of [version 3](https://github.com/SmartBFT-Go/fabric/tree/release-1.4-BFT-3) which includes only dynamic reconfiguration and periodical leader rotation but without committee selection [which is in version 4](https://github.com/SmartBFT-Go/fabric/tree/release-1.4-BFT-4).

**Comment by TianshuDing** [comment]
I found a release-2.3-BFT branch，is this from Fabric-2.3 and add the BFT consensus?

**Comment by yacovm** [comment]
Ask @muzykantov I think he added the branch

**Comment by muzykantov** [comment]
@767472021, @TianshuDing hello. There is now a working version in the release-2.3-BFT branch. You can try to build your solution based on it.

**Comment by TianshuDing** [comment]
thanks. Is there any tutorials about how to implement a new consensus in Fabric 2.X?

**Comment by muzykantov** [comment]
You can find orderers configuration at

**Comment by muzykantov** [comment]
> thanks. Is there any tutorials about how to implement a new consensus in Fabric 2.X?

Sure.

[Sample configuration (see SmartBFT section at 367 line)](https://github.com/SmartBFT-Go/fabric/blob/release-2.3-BFT/sampleconfig/configtx.yaml)

[Protobuf](https://github.com/SmartBFT-Go/fabric-protos/blob/release-2.2/orderer/smartbft/configuration.proto)

[Compiled protobuf](https://github.com/SmartBFT-Go/fabric-protos-go/blob/main/v2/orderer/smartbft/configuration.pb.go)

[Paper](https://github.com/SmartBFT-Go/SmartBFT-Go.github.io/blob/master/paper.pdf)
