### ISSUE TITLE
Question for a running sample for this smart BFT

### ISSUE THREAD

**Issue by SamYuan1990** [SmartBFT-Go/fabric#275]
Hi Guys,

Do we have any way to run this project?
As test-network?

Thanks and Regards
Sam

**Comment by yacovm** [comment]
Take a look at the recent commits in https://github.com/SmartBFT-Go/fabric-samples

**Comment by SamYuan1990** [comment]
thanks

**Comment by yacovm** [comment]
@SamYuan1990 are you at IBM? If so then ping me at yacovm@il.ibm.com
