### ISSUE TITLE
Why leader is rotating after every block creation in SBFT 2.3.0.

### ISSUE THREAD

**Issue by Pro-Novice** [SmartBFT-Go/fabric#283]
We are using Hyperledger Fabric 2.3.0 and using SBFT Consensus,
and leader is rotating after every block creation.
and we set MaxMessageCount to 10 in configtx.yaml but it is not restricting no of transactions in a block to 10. rather it is accumulating random number of transactions .
How can we configure batch size in SBFT. any suggestions.

**Comment by yacovm** [comment]
You can [disable](https://github.com/SmartBFT-Go/fabric-protos/blob/release-2.3-BFT/orderer/smartbft/configuration.proto#L57-L63) the rotation if you don't want it.

**Comment by Pro-Novice** [comment]
Thanks for your answer.
