### ISSUE TITLE
I would like to know how you test the performance

### ISSUE THREAD

**Issue by zhazhalaila** [SmartBFT-Go/fabric#285]
I tested the performance of Fabric with Fabric Caliper. But the TPS written to the smart contract in the [test report](https://hyperledger.github.io/caliper-benchmarks/fabric/performance/2.1.0/goContract/nodeSDK/submit/create-asset/) test report is only 350.6.

I see that your TPS in your paper easily exceeded 1,000, why is that? Is it because Fabric Caliper includes chaincode execution and verification in the test?

How should I test to achieve the performance claimed in your paper?

How do I test Fabric? Use Fabric Caliper or the Benchmark tool you wrote? If I want to use the Benchmark tool you wrote, how should I get it and run it?

**Comment by yacovm** [comment]
> I see that your TPS in your paper easily exceeded 1,000, why is that? Is it because Fabric Caliper includes chaincode execution and verification in the test?

The performance was tested only on the orderer, not on the smart contract execution as it happens **before** consensus. 

> How do I test Fabric? Use Fabric Caliper or the Benchmark tool you wrote? If I want to use the Benchmark tool you wrote, how should I get it and run it?

You need to make sure you saturate the orderer. With Caliper it's hard to do that, so you probably need to run many caliper instances and them sum the performance numbers each reports.

**Comment by zhazhalaila** [comment]
For example, suppose I am in the orderer folder of the fabric, and the file directory is as follows:
```
+- orderer/ 
|  |
|  +- common/                      
|  |
|  +- consensus/            
|  |
|  +- mocks/      
|  |   
|  +- sample_clients/    
```
All I need to do is to start the smartbft service under the consensus folder, and then use the client under the sample_clients folder to connect to the order for benchmark testing?

**Comment by yacovm** [comment]
What you use to benchmark the orderer is up to you

**Comment by zhazhalaila** [comment]
> What you use to benchmark the orderer is up to you

Thanks for your reply.

**Comment by zhazhalaila** [comment]
I set up a cluster of ordering nodes locally using the raft algorithm. But when I use the broadcast_config in the sample_clients folder, I find that after TLS is turned on, the client cannot connect to the ordering node. What should I do to connect to the ordering node?
