### ISSUE TITLE
optimization: Minimize signature checks when processing proposals

### ISSUE THREAD

**Issue by yacovm** [SmartBFT-Go/fabric#40]
A correct client sends its request (transaction) to all followers, and thus - all followers are bound to verify the transaction twice.

A request (transaction) is verified at two different places:

- At the Broadcast layer (followers and leader alike), via the signature filters.
- In the followers, at the time of validation of the proposal from the leader.

This makes the proposal handling costly from a CPU processing point of view. 

Note, that both the Broadcast filters and the Verifier dependency use the same method:
`Evaluate(signatureSet []*protoutil.SignedData) error`
which is implemented by a policy. 
I think we can perhaps try to optimize this by implementing a **policy provider** which creates policies for **channel writers** (the policy checked by both broadcast and BFT followers) that:

- Upon successful validation, caches the hash over the signed data (in ASN1 format). 
- Upon a verification, looks up if the said hash over the signed data has been cached, and if so - returns nil without actually verifying.

If a configuration change occurs, the policy manager instance is wiped out, and new empty caches will be created.

As long as there is no configuration change that destroys the policy manager instance (and with it - the policy provider instances and the caches...), we are replacing all ECDSA verifications of a transaction verification with a single hash (that is anyway performed as part of the signature check), and a map lookup.

This would potentially reduce the CPU overhead of verifying proposals from leaders to a minimum, because by the time a batch is cut, the transaction should have been verified by all followers.

**Comment by yacovm** [comment]
@C0rWin  @tock-ibm  @HagarMeir  wdyt?

**Comment by C0rWin** [comment]
It makes sense, in fact entries from this cache could be evicted once block with relevant transactions is committed.
